# Generated by Django 4.2.16 on 2024-11-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailwhiz_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='graduated_or_not',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
