# Generated by Django 5.1.3 on 2024-11-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailwhiz_ui', '0002_customuser_college_customuser_graduated_or_not_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gemini_api_key',
        ),
    ]
