# Generated by Django 5.1.3 on 2024-11-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailwhiz_ui', '0003_remove_customuser_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
